# Generated by Django 5.2.17 on 2026-08-21 01:57

import uuid
from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import accounts.managers


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations: ClassVar[list[object]] = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", accounts.managers.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="LoginThrottleBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("ACCOUNT", "Account"), ("ORIGIN", "Origin")],
                        max_length=16,
                    ),
                ),
                ("key_digest", models.CharField(max_length=64)),
                ("failure_count", models.PositiveIntegerField()),
                ("last_failed_at", models.DateTimeField()),
                ("blocked_until", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "blocked_until"],
                        name="acct_thr_scope_block_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key_digest"),
                        name="accounts_throttle_scope_digest_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("failure_count__gte", 1)),
                        name="accounts_throttle_failure_count_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requested_target_digest",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("ASSIGN", "Assign"), ("REVOKE", "Revoke")],
                        max_length=8,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("DENIED", "Denied"),
                            ("TARGET_NOT_FOUND", "Target not found"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed", models.BooleanField(default=False)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_changes_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_changes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["target", "occurred_at"],
                        name="acct_role_target_time_idx",
                    ),
                    models.Index(
                        fields=["requested_target_digest", "occurred_at"],
                        name="acct_role_digest_time_idx",
                    ),
                    models.Index(
                        fields=["actor", "occurred_at"], name="acct_role_actor_time_idx"
                    ),
                    models.Index(
                        fields=["result", "occurred_at"],
                        name="acct_role_result_time_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("requested_target_digest__isnull", True),
                                ("target__isnull", False),
                            ),
                            models.Q(
                                ("requested_target_digest__isnull", False),
                                ("target__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="accounts_role_target_xor_digest",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("result", "TARGET_NOT_FOUND"), ("target__isnull", True)
                            ),
                            models.Q(
                                models.Q(("result", "TARGET_NOT_FOUND"), _negated=True),
                                ("target__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="accounts_role_not_found_iff_target_null",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("result__in", ("DENIED", "TARGET_NOT_FOUND")),
                                _negated=True,
                            ),
                            ("changed", False),
                            _connector="OR",
                        ),
                        name="accounts_role_failed_never_changed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("changed", False),
                            models.Q(("result", "SUCCESS"), ("target__isnull", False)),
                            _connector="OR",
                        ),
                        name="accounts_role_changed_requires_success",
                    ),
                ],
            },
        ),
    ]
