# Generated by Django 5.2.17 on 2026-08-21 14:08

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_catalog_state(apps, schema_editor):
    catalog_state = apps.get_model("catalog", "CatalogState")
    catalog_state.objects.using(schema_editor.connection.alias).get_or_create(
        id=1,
        defaults={"track_order_revision": 0},
    )


def remove_catalog_state(apps, schema_editor):
    catalog_state = apps.get_model("catalog", "CatalogState")
    catalog_state.objects.using(schema_editor.connection.alias).filter(id=1).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="CatalogState",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("track_order_revision", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="catalog_state_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "title_key",
                    models.CharField(editable=False, max_length=480, unique=True),
                ),
                ("description", models.CharField(max_length=2000)),
                ("audience", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("INACTIVE", "Inactive"), ("ACTIVE", "Active")],
                        default="INACTIVE",
                        max_length=8,
                    ),
                ),
                ("position", models.PositiveIntegerField(unique=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("module_order_revision", models.PositiveBigIntegerField(default=0)),
                ("published_version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("position", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "position"],
                        name="catalog_track_status_pos_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1)),
                        name="catalog_track_position_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="catalog_track_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "INACTIVE"),
                            ("published_version__gte", 1),
                            _connector="OR",
                        ),
                        name="catalog_track_active_has_version",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("title_key", models.CharField(editable=False, max_length=480)),
                ("objective", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[("INACTIVE", "Inactive"), ("ACTIVE", "Active")],
                        default="INACTIVE",
                        max_length=8,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("published_version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modules",
                        to="catalog.track",
                    ),
                ),
            ],
            options={
                "ordering": ("track_id", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="TrackVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=160)),
                ("description", models.CharField(max_length=2000)),
                ("audience", models.CharField(max_length=500)),
                ("source", models.CharField(max_length=500)),
                ("reviewed_on", models.DateField()),
                (
                    "editorial_status",
                    models.CharField(choices=[("APPROVED", "Approved")], max_length=8),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="track_versions_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="catalog.track",
                    ),
                ),
            ],
            options={
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="CatalogChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("EDIT", "Edit"),
                            ("ACTIVATE", "Activate"),
                            ("DEACTIVATE", "Deactivate"),
                            ("REORDER", "Reorder"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("TRACK", "Track"), ("MODULE", "Module")], max_length=6
                    ),
                ),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                (
                    "unresolved_reference_digest",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("DENIED", "Denied"),
                            ("INVALID", "Invalid"),
                            ("CONFLICT", "Conflict"),
                            ("NOT_FOUND", "Not found"),
                        ],
                        max_length=10,
                    ),
                ),
                ("changed", models.BooleanField(default=False)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_changes_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["actor", "occurred_at"], name="catalog_change_actor_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id", "occurred_at"],
                        name="catalog_change_entity_idx",
                    ),
                    models.Index(
                        fields=[
                            "entity_type",
                            "unresolved_reference_digest",
                            "occurred_at",
                        ],
                        name="catalog_change_digest_idx",
                    ),
                    models.Index(
                        fields=["result", "occurred_at"],
                        name="catalog_change_result_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("entity_id__isnull", True),
                            ("unresolved_reference_digest__isnull", True),
                            _connector="OR",
                        ),
                        name="catalog_change_reference_exclusive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("result", "SUCCESS"), ("changed", False), _connector="OR"
                        ),
                        name="catalog_change_failed_unchanged",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("changed", False),
                            models.Q(
                                ("entity_id__isnull", False), ("result", "SUCCESS")
                            ),
                            _connector="OR",
                        ),
                        name="catalog_change_changed_success",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("result", "NOT_FOUND"), _negated=True),
                            ("unresolved_reference_digest__isnull", False),
                            _connector="OR",
                        ),
                        name="catalog_change_not_found_digest",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModuleVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=160)),
                ("objective", models.CharField(max_length=1000)),
                ("source", models.CharField(max_length=500)),
                ("reviewed_on", models.DateField()),
                (
                    "editorial_status",
                    models.CharField(choices=[("APPROVED", "Approved")], max_length=8),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="module_versions_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="catalog.module",
                    ),
                ),
            ],
            options={
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["module", "-version_number"],
                        name="catalog_module_version_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("module", "version_number"),
                        name="catalog_module_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version_number__gte", 1)),
                        name="catalog_module_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("editorial_status", "APPROVED")),
                        name="catalog_module_version_approved",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["track", "status", "position"],
                name="catalog_module_track_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("track", "title_key"), name="catalog_module_track_title_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("track", "position"),
                name="catalog_module_track_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="catalog_module_position_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="catalog_module_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "INACTIVE"),
                    ("published_version__gte", 1),
                    _connector="OR",
                ),
                name="catalog_module_active_has_version",
            ),
        ),
        migrations.AddIndex(
            model_name="trackversion",
            index=models.Index(
                fields=["track", "-version_number"], name="catalog_track_version_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="trackversion",
            constraint=models.UniqueConstraint(
                fields=("track", "version_number"), name="catalog_track_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="trackversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version_number__gte", 1)),
                name="catalog_track_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="trackversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("editorial_status", "APPROVED")),
                name="catalog_track_version_approved",
            ),
        ),
        migrations.RunPython(create_catalog_state, remove_catalog_state),
    ]
