# Generated by Django 5.2.17 on 2026-08-21

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=9,
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("published_version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_items",
                        to="catalog.module",
                    ),
                ),
            ],
            options={
                "ordering": ("module_id", "position", "id"),
                "indexes": [
                    models.Index(
                        fields=["module", "status", "position"],
                        name="catalog_content_state_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("module", "position"),
                        name="catalog_content_module_position_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1)),
                        name="catalog_content_position_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="catalog_content_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "DRAFT"),
                            ("published_version__gte", 1),
                            _connector="OR",
                        ),
                        name="catalog_content_published_has_version",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=160)),
                ("learning_objective", models.CharField(max_length=1000)),
                ("lesson_text", models.TextField()),
                ("case_prompt", models.TextField()),
                ("source", models.CharField(max_length=500)),
                ("reviewed_on", models.DateField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_versions_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="catalog.contentitem",
                    ),
                ),
            ],
            options={
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["content_item", "-version_number"],
                        name="catalog_content_version_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_item", "version_number"),
                        name="catalog_content_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version_number__gte", 1)),
                        name="catalog_content_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source", ""), _negated=True),
                        name="catalog_content_source_nonempty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("OPTIMAL", "Optimal"),
                            ("PARTIAL", "Partially adequate"),
                            ("INCORRECT", "Incorrect"),
                        ],
                        max_length=9,
                    ),
                ),
                ("consequence", models.TextField()),
                ("explanation", models.TextField()),
                (
                    "content_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="choices",
                        to="catalog.contentversion",
                    ),
                ),
            ],
            options={
                "ordering": ("content_version_id", "position", "id"),
                "default_permissions": ("view",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_version", "position"),
                        name="catalog_choice_version_position_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1), ("position__lte", 4)),
                        name="catalog_choice_position_bounded",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LabExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("objective", models.CharField(max_length=1000)),
                ("initial_prompt", models.TextField()),
                ("expected_artifact", models.TextField()),
                (
                    "verification_checklist",
                    models.JSONField(
                        validators=[catalog.models.validate_verification_checklist]
                    ),
                ),
                (
                    "content_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_exercise",
                        to="catalog.contentversion",
                    ),
                ),
            ],
            options={"default_permissions": ("view",)},
        ),
    ]
