# Generated by Django 5.2.17 on 2026-08-22

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("catalog", "0002_domain_content"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="contentversion",
            name="editorial_status",
            field=models.CharField(
                choices=[("PUBLISHED", "Published")],
                default="PUBLISHED",
                max_length=9,
            ),
        ),
        migrations.AddConstraint(
            model_name="contentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("editorial_status", "PUBLISHED")),
                name="catalog_content_version_published",
            ),
        ),
    ]
