# Generated by Django 5.2.17 on 2026-08-21

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("catalog", "0002_domain_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("WITHDRAWN", "Withdrawn")],
                        default="ACTIVE",
                        max_length=9,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="catalog.track",
                    ),
                ),
            ],
            options={
                "ordering": ("enrolled_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["account", "status", "enrolled_at"],
                        name="learn_enroll_account_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "track"),
                        name="learning_enrollment_account_track_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("OPTIMAL", "Optimal"),
                            ("PARTIAL", "Partially adequate"),
                            ("INCORRECT", "Incorrect"),
                        ],
                        max_length=9,
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("is_first_scoreable", models.BooleanField(default=False)),
                (
                    "idempotency_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="catalog.choice",
                    ),
                ),
                (
                    "content_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="catalog.contentversion",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="learning.enrollment",
                    ),
                ),
            ],
            options={
                "ordering": ("attempted_at", "id"),
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["enrollment", "attempted_at"],
                        name="learn_attempt_enrolled_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_first_scoreable", True)),
                        fields=("enrollment", "content_version"),
                        name="learning_attempt_first_scoreable_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("completed_items", models.PositiveIntegerField(default=0)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("correct_attempts", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="module_progress",
                        to="learning.enrollment",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollment_progress",
                        to="catalog.module",
                    ),
                ),
            ],
            options={
                "ordering": ("module__position", "module_id", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment", "module"),
                        name="learning_progress_enrollment_module_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("completed_items__lte", models.F("total_items"))
                        ),
                        name="learning_progress_completed_lte_total",
                    ),
                ],
            },
        ),
    ]
