# Generated by Django 5.2.17 on 2026-08-21

import uuid
from typing import ClassVar

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class AddPostgresConstraint(migrations.AddConstraint):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="WeeklySeason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_on", models.DateField(unique=True)),
                ("ends_on", models.DateField(unique=True)),
            ],
            options={
                "ordering": ("-starts_on", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("starts_on__lte", models.F("ends_on"))),
                        name="gamification_season_dates_ordered",
                    )
                ],
            },
        ),
        AddPostgresConstraint(
            model_name="weeklyseason",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=(
                    (
                        models.Func(
                            models.F("starts_on"),
                            models.F("ends_on"),
                            models.Value("[]"),
                            function="DATERANGE",
                        ),
                        "&&",
                    ),
                ),
                name="gamification_season_no_overlap",
            ),
        ),
        migrations.CreateModel(
            name="ScoreEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cause", models.CharField(max_length=64)),
                ("amount", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "idempotency_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="score_event",
                        to="learning.attempt",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["cause", "occurred_at"],
                        name="gamification_score_cause_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("cause", "attempt"), _negated=True),
                            ("attempt__isnull", False),
                            _connector="OR",
                        ),
                        name="gamification_score_attempt_required",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Streak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_length", models.PositiveIntegerField(default=0)),
                ("longest_length", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longest_length__gte", models.F("current_length"))
                        ),
                        name="gamification_streak_longest_gte_current",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SeasonParticipation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weekly_points", models.PositiveIntegerField(default=0)),
                ("correct_scoreable_attempts", models.PositiveIntegerField(default=0)),
                ("total_scoreable_attempts", models.PositiveIntegerField(default=0)),
                ("completed_sessions", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="season_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="gamification.weeklyseason",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "-weekly_points",
                    "account__display_name",
                    "account_id",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("season", "account"),
                        name="gamification_participation_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "correct_scoreable_attempts__lte",
                                models.F("total_scoreable_attempts"),
                            )
                        ),
                        name="gamification_participation_correct_lte_total",
                    ),
                ],
            },
        ),
    ]
